// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwekdybjftofsogrhfeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZWtkeWJqZnRvZnNvZ3JoZmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjQzODksImV4cCI6MjA2OTQwMDM4OX0.OGYN3iqUQumB4SoVf63HcAQR1M47rl1Mxb51v_IPCA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});